### ISSUE TITLE
Use C keywords for CPP syntax

### ISSUE THREAD

**Issue by pzehner** [jiangxincode/mpi.vim#3]
Hello there, thank you for this plugin.

Since the MPI C++ API has been discontinued, C++ programmers have to use the C API instead. However, when working on C++ files with this plugin, basic MPI keywords such as `MPI_COMM_WORLD` are not highlighted. I think the simplest solution is to include C keywords highlight definitions in the list of C++ keywords.

**Comment by jiangxincode** [comment]
OK, I will try to fix this issue ASAP
